### ISSUE TITLE
Chrome on heroku

### ISSUE THREAD

**Issue by mishailovic** [SpEcHiDe/UniBorg#48]
When i am trying to use module "screencapture" it says "need to install Google Chrome. Module Stopping.", But I'm hosting my userbot on heroku. How to install chrome on it?

**Comment by muhammedfurkan** [comment]
add this 

https://github.com/heroku/heroku-buildpack-google-chrome

https://github.com/heroku/heroku-buildpack-chromedriver

**Comment by mishailovic** [comment]
> add this
> 
> https://github.com/heroku/heroku-buildpack-google-chrome
> 
> https://github.com/heroku/heroku-buildpack-chromedriver

Btw, and I use ftg, maybe this is the problem?

**Comment by muhammedfurkan** [comment]
why do you write to UniBorg repo even though you use ftg?

**Comment by penn5** [comment]
> why do you write to UniBorg repo even though you use ftg?

Because FTG supports UniBorg modules

> > add this
> > https://github.com/heroku/heroku-buildpack-google-chrome
> > https://github.com/heroku/heroku-buildpack-chromedriver
> 
> Btw, and I use ftg, maybe this is the problem?

No, that won't be a problem. Just add the buildpacks.

**Comment by mishailovic** [comment]
> > why do you write to UniBorg repo even though you use ftg?
> 
> Because FTG supports UniBorg modules
> 
> > > add this
> > > https://github.com/heroku/heroku-buildpack-google-chrome
> > > https://github.com/heroku/heroku-buildpack-chromedriver
> > 
> > 
> > Btw, and I use ftg, maybe this is the problem?
> 
> No, that won't be a problem. Just add the buildpacks.

Probably a stupid question.  It says that the buildpacks will be applied after the next deploy.  How do I make a deploy without updating?
