### ISSUE TITLE
uploading subfolders doesnt works

### ISSUE THREAD

**Issue by ghost** [SpEcHiDe/UniBorg#65]
when I try to upload a dir, it not uploads sub-dirs
example: 

**_upload1_**
_some files here_
**_- thisisasubdir_**
_- some files here_
**_-- thisissubsubdir_**
_-- some files here_

when I give command 
.uploadir upload1

it's not uploading subdirs. how to upload all of files (with all subdir files?)
you may try with a little sample. please fix. thank you :)

**Comment by prono69** [comment]
Me nub :(

**Comment by GauthamramRavichandran** [comment]
we need to recursively list the files and start upload.I'll fix the issue

**Comment by GauthamramRavichandran** [comment]
Hi @qorcfotian, the code already recursively uploads the file.
Could you send any logs to understand what's the issue here

**Comment by SpEcHiDe** [comment]
Try having a directory in the below format:

ROOT
- A
  - B
    - one.txt
  - C
  - D
    - two.txt

I think with the current code, it will get stuck when it reaches the directory C.

C is an empty directory.

**Comment by GauthamramRavichandran** [comment]
Interesting, the recursive list is not getting files after an empty dir. I'll look into this
Edit: It's not listing the second directory itself, even it has files

**Comment by gautamajay52** [comment]
I have pulled a request for upload.py file.
And now it uploads all the files present in any subfolders of the specified folder in .uploadir command.

Tested🙄
