### ISSUE TITLE
remove use less plugins

### ISSUE THREAD

**Issue by SpEcHiDe** [SpEcHiDe/UniBorg#70]
openload and verystream are dead. read https://t.me/c/1220993104/380787 

- [x] upload_to_verystream.py
- [ ] dagd.py
- [ ] qr_code.py
- [x] rapidleech.py
- [ ] screencapture.py
- [ ] tb_button.py
- [ ] wikimedia.py
- [ ] xtools.py

**Comment by GauthamramRavichandran** [comment]
Could we add it in an `outdated/archived plugins` directory. lesser maintenance in that way, instead of removing from repo

**Comment by SpEcHiDe** [comment]
The deleted plugins can be found in this commit: https://github.com/SpEcHiDe/UniBorg/commit/6d32833ddee3ede98bab389099d131a31d3967f5
