### ISSUE TITLE
fix these shit

### ISSUE THREAD

**Issue by SpEcHiDe** [SpEcHiDe/UniBorg#73]
https://github.com/SpEcHiDe/UniBorg/blob/master/dbplugins/notification_mtab_manager.py#L27

- [ ] https://t.me/c/1220993104/248405 
- [ ] https://t.me/c/1220993104/119402
- [ ] https://t.me/c/1220993104/5633
- [ ] https://t.me/c/1256850030/9461

**Comment by GauthamramRavichandran** [comment]
Could you share the public link? I can't access it from telegram desktop

**Comment by SpEcHiDe** [comment]
sorry. But this is something I am working on. :((
