### ISSUE TITLE
Fix the variable names

### ISSUE THREAD

**Issue by SpEcHiDe** [SpEcHiDe/UniBorg#84]
- [ ] https://github.com/SpEcHiDe/UniBorg/blob/b359585b287ce1376d0ff834881eb2127f47b8bd/stdplugins/ukinti.py#L5

**Comment by GauthamramRavichandran** [comment]
Anyone working on this? I'm glad to.

**Comment by SpEcHiDe** [comment]
sure. You can.

**Comment by GauthamramRavichandran** [comment]
#91 - Fixed
