### ISSUE TITLE
Problem with Aria Two Plugin

### ISSUE THREAD

**Issue by thatshowitworks** [SpEcHiDe/UniBorg#90]
On adding a magnet the download gets successful but god knows to which directory it gets downloaded to.I checked TMP_DOWNLOAD_DIRECTORY and root directory but the weren't there.So, I can't even upload the aria2 downloaded files to telegram which makes the plugin useless.Please look after this🥺

**Comment by theRay1s** [comment]
@thatshowitworks 

Torrent files are in folders so upload them to drive 
 Using command 
.gdrivedir
