### ISSUE TITLE
[Help] How do I provide torrent functionality in Uniborg?

### ISSUE THREAD

**Issue by sxrea** [SpEcHiDe/UniBorg#94]
Hello!

I want to download torrents on Uniborg.

But in the setup of the heroku, I do not know what to write in the **value** section below.
```
"HASH_TO_TORRENT_API":
 {
     "description": "This is required for the hash to torrent file functionality to work.",
     "value": "https://example.com/torrent/{}",
     "required": false
```
Can you help me...
Thanks.

**Comment by SpEcHiDe** [comment]
HASH_TO_TORRENT_API is an entirely different functionality, and is NOT FOR DOWNLOADING TORRENT files. 

you can read the aria_two.py code to know how to DOWNLOAD TORRENT files.
